function plot_avg(name, avgArea, avgMyo,t,t_unit)

% Determine average area and myosin intensity for all cells at each time
% point
% INPUT: name=cell that contains title of plot
%        dataArea, dataMyo=input data matrices (can be clipped)
%        t=time matrix 
%        t_unit=specifies unit (frames or seconds)
% OUTPUT: plots avgerages of area and myosin on same plot vs. time



% Plot and formatting
[AX,H1,H2]=plotyy(t,avgArea(:,1),t,avgMyo(:,1),'plot');
    allAxes=findall(gcf,'Type','axes');
    set(allAxes,'FontName','Arial',...
            'FontSize',10,...
            'FontWeight','bold',...
            'LineWidth',4,...
            'XLim',[0,max(t)]);
    % Labeling & formatting Apical area y-axis
    set(get(AX(1),'Ylabel'),'String',...
             'Mean apical area constriction (um^2)',...
             'FontSize',12,...
             'FontWeight','bold');
%     set(AX(1),'YTick',[0 10 20 30 40 50]);
    % Labeling & formatting Myosin intensity y-axis
    set(get(AX(2),'Ylabel'),'String',...
            'Mean myosin intensity accumulation (a.u.)',...
            'FontSize',12,...
            'FontWeight','bold');
%     set(AX(2),'YTick',[0 2000 4000 8000 10000 12000]);
    % Labeling & formatting x-axis
    xlabel(strcat('Time (',t_unit,')'),...
            'FontSize',12,...
            'FontWeight','bold');
    % Labeling & formating title 
    title(name,...
            'FontSize',14,...
            'FontWeight','bold');
    set(H1,'LineWidth',2);
    set(H2,'LineWidth',2);